"""Generates the config.yaml the apple-music-downloader container reads.

Why this module exists
---------------------
The downloader binary loads ``config.yaml`` from its working directory before
it parses any arguments, and there is no ``--config`` flag to redirect it.
Upstream's own README says to supply the file yourself (the repo tracks
``config.yaml.example`` and deliberately does not track ``config.yaml``) and
documents the container path as ``/app/config.yaml``.

The published ``ghcr.io/zhaarey/apple-music-downloader`` image does bake a
``config.yaml`` into ``/app``, but that baked copy is **malformed**: the build
appends its ``/downloads`` overrides with ``>>`` onto a file that has no
trailing newline, so two keys end up fused onto one physical line::

    proxy: ""alac-save-folder: "/downloads/ALAC"

The binary rejects it outright::

    load Config failed: yaml: line 97: did not find expected key

The image also ships no ``config.yaml.example``, so the usual
``cp config.yaml.example config.yaml`` remedy is unavailable inside it, and
Audora only *pulls* this image (never builds it) so it cannot patch the file at
build time either.

So Audora writes its own valid config and bind-mounts it over
``/app/config.yaml``. ``/app`` holds nothing but that file (the binary lives at
``/usr/local/bin/apple-music-dl``), so the mount hides nothing needed.

The generated config carries every key upstream defines — verified as an exact
54-key match against the image's own copy — and changes only what Audora must
control: the save folders (pointed into the ``/downloads`` bind mount) and the
wrapper ports.

No credentials are written here: the downloader obtains its tokens through the
wrapper, and the token fields keep their upstream placeholder values.
"""
import os
from typing import Dict

from logger import get_logger

logger = get_logger("downloader-config")

# Container-side path the binary reads. Fixed by the image's WORKDIR (/app) and
# the binary's relative open of "config.yaml"; also the path upstream's README
# documents for the bind mount.
CONTAINER_CONFIG_PATH = "/app/config.yaml"

# Container-side root of the downloads bind mount.
CONTAINER_DOWNLOADS = "/downloads"

# Wrapper service ports (see wrapper_manager). The downloader reaches these
# over the host network, so 127.0.0.1 is correct with network_mode="host".
DECRYPT_PORT = 10020
M3U8_PORT = 20020

# Quality ceilings. Audora always downloads the lossless ALAC source and then
# converts it to FLAC itself (see flac_converter), so there is no user-facing
# format choice and no per-preset table: one set of maxima applies to every
# download. These ceilings exist ONLY in config.yaml, which is why the file is
# still regenerated before each run rather than written once.
#
# Accepted values, from the image's own comments:
#   alac-max  192000 | 96000 | 48000 | 44100
#   atmos-max 2768 | 2448
#   aac-type  aac-lc | aac | aac-binaural | aac-downmix
#
# atmos-max and aac-type are kept at upstream's maxima even though Audora never
# passes --atmos or --aac: the keys must be present and valid for the binary to
# accept the file at all.
_QUALITY_CEILINGS: Dict[str, object] = {
    "alac-max": 192000,
    "atmos-max": 2768,
    "aac-type": "aac-lc",
}

# What the user ends up with. The download itself is lossless ALAC; Audora
# converts it to FLAC before the track is reported as ready, because Chromium
# (and so Electron) cannot decode ALAC and could never play it back.
OUTPUT_FORMAT = "flac"

# Subfolder per format, under the mount. Keeping formats separate mirrors the
# upstream layout (which used "AM-DL downloads", "AM-DL-Atmos downloads", ...).
_SAVE_FOLDERS = {
    "alac-save-folder": f"{CONTAINER_DOWNLOADS}/ALAC",
    "atmos-save-folder": f"{CONTAINER_DOWNLOADS}/Atmos",
    "aac-save-folder": f"{CONTAINER_DOWNLOADS}/AAC",
    # Upstream's appended block omitted this one, which would have left music
    # videos saving to a relative path inside the container — lost on exit.
    "mv-save-folder": f"{CONTAINER_DOWNLOADS}/MV",
}


def resolve_format(fmt: str) -> str:
    """Deprecated shim: Audora is FLAC-only and ignores any requested format.

    Kept so an older caller cannot crash the app, and so the reason the concept
    disappeared is recorded next to where it used to live.
    """
    if fmt:
        logger.debug(f"Ignoring requested format {fmt!r}: Audora downloads FLAC only")
    return OUTPUT_FORMAT


def build_config() -> str:
    """Return the full config.yaml text for the downloader container.

    Written from scratch rather than patched from the image's copy, so the
    result never depends on that (currently broken) file's contents.

    Takes no format argument: Audora always downloads the lossless ALAC source
    and converts it to FLAC afterwards, so there is nothing for the caller to
    choose.
    """
    lines = [
        "# Generated by Audora — rewritten before every download.",
        "#",
        "# Audora writes this file and bind-mounts it over /app/config.yaml,",
        "# because the published image ships a malformed config (an appended",
        "# save-folder key fused onto the proxy line, making the YAML invalid)",
        "# and contains no config.yaml.example to copy from.",
        "",
        "# --- Credentials -------------------------------------------------------",
        "# Left at upstream placeholders on purpose: the downloader obtains what",
        "# it needs through the wrapper, so no secrets are written to this file.",
        'media-user-token: "your-media-user-token"',
        'authorization-token: "your-authorization-token"',
        'storefront: ""',
        "",
        "# --- Output locations (Audora-controlled) ------------------------------",
        "# Absolute paths inside the /downloads bind mount, so finished files",
        "# land in the user's downloads folder on the host.",
    ]
    for key, value in _SAVE_FOLDERS.items():
        lines.append(f'{key}: "{value}"')

    lines += [
        "",
        "# --- Wrapper services --------------------------------------------------",
        "# Reached over the host network (container runs with network_mode=host).",
        f'decrypt-m3u8-port: "127.0.0.1:{DECRYPT_PORT}"',
        f'get-m3u8-port: "127.0.0.1:{M3U8_PORT}"',
        "get-m3u8-from-device: true",
        "",
        "# --- Quality (always the lossless ALAC source) -------------------------",
        f"alac-max: {_QUALITY_CEILINGS['alac-max']}",
        f"atmos-max: {_QUALITY_CEILINGS['atmos-max']}",
        f"aac-type: {_QUALITY_CEILINGS['aac-type']}",
        "get-m3u8-mode: hires",
        "limit-max: 200",
        "mv-audio-type: atmos",
        "mv-max: 2160",
        "alac-fix: false",
        "",
        "# --- Lyrics ------------------------------------------------------------",
        'language: ""',
        'lrc-type: "lyrics"',
        'lrc-format: "lrc"',
        "embed-lrc: true",
        "save-lrc-file: false",
        "",
        "# --- Artwork -----------------------------------------------------------",
        "embed-cover: true",
        "cover-size: 5000x5000",
        "cover-format: jpg",
        "save-artist-cover: false",
        "save-animated-artwork: false",
        "emby-animated-artwork: false",
        "dl-albumcover-for-playlist: false",
        "",
        "# --- Tagging -----------------------------------------------------------",
        "tag-sort-order: true",
        "tag-itunes-id: true",
        "use-songinfo-for-playlist: false",
        "",
        "# --- Naming ------------------------------------------------------------",
        'album-folder-format: "{AlbumName}"',
        'playlist-folder-format: "{PlaylistName}"',
        'song-file-format: "{SongNumer}. {SongName}"',
        'artist-folder-format: "{UrlArtistName}"',
        'explicit-choice: "[E]"',
        'clean-choice: "[C]"',
        'apple-master-choice: "[M]"',
        "",
        "# --- Runtime -----------------------------------------------------------",
        "max-memory-limit: 256",
        "# false so one bad track does not abort a whole album.",
        "exit-on-error: false",
        'proxy: ""',
        "",
        "# --- Post-download conversion (deliberately OFF) -----------------------",
        "# Audora converts ALAC -> FLAC itself, in flac_converter.py, using the",
        "# ffmpeg it bakes into its own downloader image. The downloader's own",
        "# conversion is left off on purpose: its behaviour here is unverified and",
        "# it defaults to convert-keep-original:false, so a failure would delete",
        "# the lossless source and leave nothing behind. Converting in Audora",
        "# means every output is validated before its source is removed, and the",
        "# UI can report a real converted/total count instead of a guess.",
        "convert-after-download: false",
        'convert-format: "flac"',
        "convert-keep-original: false",
        "convert-skip-if-source-matches: true",
        'ffmpeg-path: "ffmpeg"',
        'convert-extra-args: ""',
        "convert-with-metadata: true",
        "convert-warn-lossy-to-lossless: true",
        "convert-skip-lossy-to-lossless: true",
        "convert-check-bad-alac: false",
        "convert-delete-bad-alac: false",
    ]
    # Trailing newline — the missing one upstream is the whole reason this
    # module exists. Anything appending to this file must start on a new line.
    return "\n".join(lines) + "\n"


def write_config(directory: str) -> str:
    """Write the config into ``directory`` and return its full path.

    Overwrites any previous file so a stale config can never be reused, and so
    an upgrade from a format-selecting build cannot leave a file behind that no
    longer matches what Audora does.

    Raises ``OSError`` if the file cannot be written; the caller surfaces that
    rather than starting a container that is guaranteed to fail.
    """
    os.makedirs(directory, exist_ok=True)
    path = os.path.join(directory, "config.yaml")
    # newline="\n" so the file keeps LF endings on Windows: the container reads
    # it as Linux text, and stray CRs would corrupt quoted values.
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(build_config())
    logger.info(f"Wrote downloader config to {path}")
    return path


def save_subfolders() -> Dict[str, str]:
    """The container-side save folders, for callers that need to pre-create."""
    return dict(_SAVE_FOLDERS)
