directories:
  output: dist-electron
  buildResources: build
appId: com.audora.app
productName: Audora
files:
  - filter:
      - dist/**/*
      - electron/**/*
extraResources:
  - from: ../backend/dist/backend.exe
    to: backend.exe
win:
  target: nsis
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
electronVersion: 40.10.6
