// Generated by scripts/prepare-music.mjs. Do not scatter song paths across components.

export type Song = {
  id: string;
  title: string;
  artist: string;
  audioSrc: string;
  coverSrc: string;
  durationSeconds: number;
  sourceCodec: string;
};

export const SONGS = [
  {
    "id": "a-dark-knight-james-newton-howard-hans-zimmer",
    "title": "A Dark Knight",
    "artist": "James Newton Howard & Hans Zimmer",
    "audioSrc": "/music/a-dark-knight-james-newton-howard-hans-zimmer/audio.mp3",
    "coverSrc": "/music/a-dark-knight-james-newton-howard-hans-zimmer/cover.webp",
    "durationSeconds": 975,
    "sourceCodec": "ALAC"
  },
  {
    "id": "aerodynamic-daft-punk",
    "title": "Aerodynamic",
    "artist": "Daft Punk",
    "audioSrc": "/music/aerodynamic-daft-punk/audio.flac",
    "coverSrc": "/music/aerodynamic-daft-punk/cover.webp",
    "durationSeconds": 213,
    "sourceCodec": "FLAC"
  },
  {
    "id": "automhate-memories-disciple",
    "title": "Automhate - Memories",
    "artist": "Disciple ♛ ♜ ♞",
    "audioSrc": "/music/automhate-memories-disciple/audio.flac",
    "coverSrc": "/music/automhate-memories-disciple/cover.webp",
    "durationSeconds": 235,
    "sourceCodec": "FLAC"
  },
  {
    "id": "da-funk-daft-punk",
    "title": "Da Funk",
    "artist": "Daft Punk",
    "audioSrc": "/music/da-funk-daft-punk/audio.flac",
    "coverSrc": "/music/da-funk-daft-punk/cover.webp",
    "durationSeconds": 329,
    "sourceCodec": "FLAC"
  },
  {
    "id": "i-have-something-to-tell-you-automhate",
    "title": "I have something to tell you",
    "artist": "Automhate",
    "audioSrc": "/music/i-have-something-to-tell-you-automhate/audio.flac",
    "coverSrc": "/music/i-have-something-to-tell-you-automhate/cover.webp",
    "durationSeconds": 221,
    "sourceCodec": "FLAC"
  },
  {
    "id": "i-m-not-a-hero-james-newton-howard-hans-zimmer",
    "title": "I'm Not a Hero",
    "artist": "James Newton Howard & Hans Zimmer",
    "audioSrc": "/music/i-m-not-a-hero-james-newton-howard-hans-zimmer/audio.mp3",
    "coverSrc": "/music/i-m-not-a-hero-james-newton-howard-hans-zimmer/cover.webp",
    "durationSeconds": 394,
    "sourceCodec": "ALAC"
  },
  {
    "id": "no-time-for-caution-hans-zimmer",
    "title": "No Time for Caution",
    "artist": "Hans Zimmer",
    "audioSrc": "/music/no-time-for-caution-hans-zimmer/audio.mp3",
    "coverSrc": "/music/no-time-for-caution-hans-zimmer/cover.webp",
    "durationSeconds": 246,
    "sourceCodec": "ALAC"
  },
  {
    "id": "robot-rock-daft-punk",
    "title": "Robot Rock",
    "artist": "Daft Punk",
    "audioSrc": "/music/robot-rock-daft-punk/audio.flac",
    "coverSrc": "/music/robot-rock-daft-punk/cover.webp",
    "durationSeconds": 288,
    "sourceCodec": "FLAC"
  },
  {
    "id": "l-amour-impitoyable-shiro-sagisu",
    "title": "L'Amour Impitoyable",
    "artist": "Shiro Sagisu",
    "audioSrc": "/music/l-amour-impitoyable-shiro-sagisu/audio.flac",
    "coverSrc": "/music/l-amour-impitoyable-shiro-sagisu/cover.webp",
    "durationSeconds": 140,
    "sourceCodec": "FLAC"
  },
  {
    "id": "solo-automhate",
    "title": "Solo",
    "artist": "Automhate",
    "audioSrc": "/music/solo-automhate/audio.flac",
    "coverSrc": "/music/solo-automhate/cover.webp",
    "durationSeconds": 195,
    "sourceCodec": "FLAC"
  },
  {
    "id": "veridis-quo-daft-punk",
    "title": "Veridis Quo",
    "artist": "Daft Punk",
    "audioSrc": "/music/veridis-quo-daft-punk/audio.flac",
    "coverSrc": "/music/veridis-quo-daft-punk/cover.webp",
    "durationSeconds": 345,
    "sourceCodec": "FLAC"
  },
  {
    "id": "why-so-serious-hans-zimmer-james-newton-howard",
    "title": "Why So Serious?",
    "artist": "Hans Zimmer & James Newton Howard",
    "audioSrc": "/music/why-so-serious-hans-zimmer-james-newton-howard/audio.mp3",
    "coverSrc": "/music/why-so-serious-hans-zimmer-james-newton-howard/cover.webp",
    "durationSeconds": 554,
    "sourceCodec": "ALAC"
  }
] as const satisfies readonly Song[];
