import { copyFile, mkdir, readdir, writeFile } from 'node:fs/promises';
import { basename, extname, join, relative, resolve } from 'node:path';
import { spawn } from 'node:child_process';
import { parseFile } from 'music-metadata';
import sharp from 'sharp';
import ffmpegPath from 'ffmpeg-static';

const projectRoot = resolve(import.meta.dirname, '..');
const publicRoot = resolve(projectRoot, 'public/music');
const sourceArg = process.argv[2] || process.env.AUDORA_SONG_SOURCE;

if (!sourceArg) {
  console.error('Usage: npm run prepare:music -- <source-folder>');
  process.exit(1);
}

const sourceRoot = resolve(sourceArg);
if (relative(projectRoot, publicRoot).startsWith('..')) throw new Error('Music output must stay inside the marketing project.');

const slugify = value => value.normalize('NFKD').replace(/[\u0300-\u036f]/g, '').toLowerCase()
  .replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 70) || 'song';

const runFfmpeg = (input, output) => new Promise((resolveRun, reject) => {
  const child = spawn(ffmpegPath, ['-hide_banner', '-loglevel', 'error', '-y', '-i', input, '-map', '0:a:0',
    '-map_metadata', '-1', '-codec:a', 'libmp3lame', '-q:a', '2', output], { stdio: 'inherit' });
  child.once('error', reject);
  child.once('exit', code => code === 0 ? resolveRun() : reject(new Error(`ffmpeg exited with code ${code}`)));
});

const files = (await readdir(sourceRoot, { withFileTypes: true }))
  .filter(entry => entry.isFile() && ['.flac', '.m4a', '.mp3', '.ogg'].includes(extname(entry.name).toLowerCase()))
  .map(entry => entry.name).sort((a, b) => a.localeCompare(b));

if (!files.length) throw new Error('No supported songs found in the source folder.');

await mkdir(publicRoot, { recursive: true });
const songs = [];
const usedSlugs = new Set();

for (const filename of files) {
  const input = join(sourceRoot, filename);
  const metadata = await parseFile(input);
  const title = metadata.common.title?.trim() || basename(filename, extname(filename)).replace(/[_-]+/g, ' ').trim();
  const artist = metadata.common.artist?.trim() || 'Unknown artist';
  const baseSlug = slugify(`${title}-${artist}`);
  let slug = baseSlug;
  for (let suffix = 2; usedSlugs.has(slug); suffix++) slug = `${baseSlug}-${suffix}`;
  usedSlugs.add(slug);

  const songRoot = join(publicRoot, slug);
  await mkdir(songRoot, { recursive: true });

  const sourceExtension = extname(filename).toLowerCase();
  const isAlac = metadata.format.codec?.toUpperCase() === 'ALAC';
  const audioName = isAlac ? 'audio.mp3' : `audio${sourceExtension}`;
  const audioOutput = join(songRoot, audioName);
  if (isAlac) await runFfmpeg(input, audioOutput);
  else await copyFile(input, audioOutput);

  const picture = metadata.common.picture?.find(item => item.type === 'Cover (front)') || metadata.common.picture?.[0];
  if (!picture) throw new Error(`No embedded cover artwork found in ${filename}`);
  await sharp(picture.data).rotate().resize(900, 900, { fit: 'cover' })
    .webp({ quality: 84, effort: 6 }).toFile(join(songRoot, 'cover.webp'));

  songs.push({
    id: slug,
    title,
    artist,
    audioSrc: `/music/${slug}/${audioName}`,
    coverSrc: `/music/${slug}/cover.webp`,
    durationSeconds: Math.round(metadata.format.duration || 0),
    sourceCodec: metadata.format.codec || sourceExtension.slice(1).toUpperCase(),
  });
  console.log(`Prepared ${title} — ${artist}${isAlac ? ' (ALAC → MP3 web copy)' : ''}`);
}

const moduleSource = `// Generated by scripts/prepare-music.mjs. Do not scatter song paths across components.\n\n`
  + `export type Song = {\n  id: string;\n  title: string;\n  artist: string;\n  audioSrc: string;\n  coverSrc: string;\n  durationSeconds: number;\n  sourceCodec: string;\n};\n\n`
  + `export const SONGS = ${JSON.stringify(songs, null, 2)} as const satisfies readonly Song[];\n`;
await writeFile(join(projectRoot, 'lib/songs.generated.ts'), moduleSource);
console.log(`Prepared ${songs.length} songs in public/music with centralized metadata in lib/songs.generated.ts.`);
