create table public.site_visitors (
  visitor_id uuid primary key,
  first_seen timestamptz not null default now(),
  last_seen timestamptz not null default now(),
  constraint site_visitors_seen_order check (last_seen >= first_seen)
);

create table public.feedback_submissions (
  id bigint generated by default as identity primary key,
  submission_token uuid not null default gen_random_uuid() unique,
  name text not null check (char_length(name) between 2 and 80),
  email text check (email is null or char_length(email) <= 254),
  role text check (role is null or char_length(role) <= 100),
  rating smallint not null check (rating between 1 and 5),
  message text not null check (char_length(message) between 20 and 1200),
  consent_to_publish boolean not null default false,
  status text not null default 'pending' check (status in ('pending', 'published', 'rejected')),
  created_at timestamptz not null default now(),
  published_at timestamptz,
  constraint published_feedback_requires_consent check (status <> 'published' or consent_to_publish)
);

create table public.site_metrics (
  singleton boolean primary key default true check (singleton),
  active_visitors_30d bigint not null default 0,
  visitors_total bigint not null default 0,
  published_reviews bigint not null default 0,
  updated_at timestamptz not null default now()
);

insert into public.site_metrics (singleton) values (true);

create index site_visitors_last_seen_idx on public.site_visitors (last_seen desc);
create index feedback_publication_idx on public.feedback_submissions (published_at desc)
where status = 'published' and consent_to_publish;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

alter table public.site_visitors enable row level security;
alter table public.feedback_submissions enable row level security;
alter table public.site_metrics enable row level security;

revoke all on table public.site_visitors from anon, authenticated, service_role;
revoke all on table public.feedback_submissions from anon, authenticated, service_role;
revoke all on table public.site_metrics from anon, authenticated, service_role;
revoke all on sequence public.feedback_submissions_id_seq from anon, authenticated, service_role;

create policy "Anonymous visitors can record a new browser"
on public.site_visitors for insert to anon, authenticated
with check (
  visitor_id is not null
  and last_seen >= first_seen
  and last_seen <= now() + interval '5 minutes'
);

create policy "Anonymous visitors can refresh a browser timestamp"
on public.site_visitors for update to anon, authenticated
using (visitor_id is not null)
with check (
  visitor_id is not null
  and last_seen >= first_seen
  and last_seen <= now() + interval '5 minutes'
);

create policy "Anyone can submit pending feedback"
on public.feedback_submissions for insert to anon, authenticated
with check (status = 'pending');

create policy "Anyone can read consented published reviews"
on public.feedback_submissions for select to anon, authenticated
using (status = 'published' and consent_to_publish);

create policy "Anyone can read aggregate site metrics"
on public.site_metrics for select to anon, authenticated
using (singleton);

grant insert (submission_token, name, email, role, rating, message, consent_to_publish)
  on public.feedback_submissions to anon, authenticated;
grant usage on sequence public.feedback_submissions_id_seq to anon, authenticated;
grant select (id, name, role, rating, message, published_at, status, consent_to_publish)
  on public.feedback_submissions to anon, authenticated;
grant select on public.site_metrics to anon, authenticated;

create or replace function private.record_site_visit(p_visitor_id uuid)
returns void
language sql
security definer
set search_path = ''
as $$
  insert into public.site_visitors (visitor_id, last_seen)
  values (p_visitor_id, now())
  on conflict (visitor_id) do update
    set last_seen = excluded.last_seen;
$$;

create or replace function public.record_site_visit(p_visitor_id uuid)
returns void
language sql
security invoker
set search_path = ''
as $$
  select private.record_site_visit(p_visitor_id);
$$;

create or replace function public.submit_feedback(
  p_submission_token uuid,
  p_name text,
  p_email text,
  p_role text,
  p_rating smallint,
  p_message text,
  p_consent_to_publish boolean
)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
begin
  insert into public.feedback_submissions (
    submission_token,
    name,
    email,
    role,
    rating,
    message,
    consent_to_publish
  ) values (
    p_submission_token,
    trim(p_name),
    nullif(trim(p_email), ''),
    nullif(trim(p_role), ''),
    p_rating,
    trim(p_message),
    p_consent_to_publish
  )
  on conflict (submission_token) do nothing;
end;
$$;

create or replace function public.get_public_evidence()
returns jsonb
language sql
stable
security invoker
set search_path = ''
as $$
  select jsonb_build_object(
    'activeVisitors30d', metrics.active_visitors_30d,
    'visitorsTotal', metrics.visitors_total,
    'publishedReviews', metrics.published_reviews
  ) from public.site_metrics as metrics where metrics.singleton;
$$;

create or replace function public.get_public_reviews(p_limit integer default 6)
returns table (
  id bigint,
  name text,
  role text,
  rating smallint,
  message text,
  published_at timestamptz
)
language sql
stable
security invoker
set search_path = ''
as $$
  select
    feedback.id,
    feedback.name,
    feedback.role,
    feedback.rating,
    feedback.message,
    feedback.published_at
  from public.feedback_submissions as feedback
  where feedback.status = 'published'
    and feedback.consent_to_publish
  order by feedback.published_at desc nulls last, feedback.id desc
  limit least(greatest(coalesce(p_limit, 6), 1), 12);
$$;

create or replace function private.refresh_site_metrics()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.site_metrics set
    active_visitors_30d = (
      select count(*) from public.site_visitors
      where last_seen >= now() - interval '30 days'
    ),
    visitors_total = (select count(*) from public.site_visitors),
    published_reviews = (
      select count(*) from public.feedback_submissions
      where status = 'published' and consent_to_publish
    ),
    updated_at = now()
  where singleton;
  return null;
end;
$$;

create or replace function public.set_feedback_published_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if new.status = 'published' then
    new.published_at = coalesce(new.published_at, now());
  else
    new.published_at = null;
  end if;
  return new;
end;
$$;

create trigger feedback_publication_timestamp
before update of status on public.feedback_submissions
for each row execute function public.set_feedback_published_at();

create trigger feedback_publication_on_insert
before insert on public.feedback_submissions
for each row execute function public.set_feedback_published_at();

create trigger visitor_metrics_insert
after insert on public.site_visitors
for each statement execute function private.refresh_site_metrics();

create trigger visitor_metrics_update
after update of last_seen on public.site_visitors
for each statement execute function private.refresh_site_metrics();

create trigger visitor_metrics_delete
after delete on public.site_visitors
for each statement execute function private.refresh_site_metrics();

create trigger feedback_metrics_insert
after insert on public.feedback_submissions
for each statement execute function private.refresh_site_metrics();

create trigger feedback_metrics_update
after update of status, consent_to_publish on public.feedback_submissions
for each statement execute function private.refresh_site_metrics();

create trigger feedback_metrics_delete
after delete on public.feedback_submissions
for each statement execute function private.refresh_site_metrics();

revoke execute on function public.record_site_visit(uuid) from public;
revoke execute on function public.submit_feedback(uuid, text, text, text, smallint, text, boolean) from public;
revoke execute on function public.get_public_evidence() from public;
revoke execute on function public.get_public_reviews(integer) from public;
revoke execute on function private.record_site_visit(uuid) from public;
revoke execute on function private.refresh_site_metrics() from public, anon, authenticated;
revoke execute on function public.set_feedback_published_at() from public;

grant usage on schema private to anon, authenticated;
grant execute on function private.record_site_visit(uuid) to anon, authenticated;
grant execute on function public.record_site_visit(uuid) to anon, authenticated;
grant execute on function public.submit_feedback(uuid, text, text, text, smallint, text, boolean) to anon, authenticated;
grant execute on function public.get_public_evidence() to anon, authenticated;
grant execute on function public.get_public_reviews(integer) to anon, authenticated;

do $$
begin
  if to_regprocedure('public.rls_auto_enable()') is not null then
    execute 'revoke execute on function public.rls_auto_enable() from public, anon, authenticated';
  end if;
end;
$$;

comment on table public.site_visitors is 'Anonymous browser installations used only for aggregate Audora website activity.';
comment on table public.feedback_submissions is 'Private feedback inbox. A row becomes public only after consent and manual publication.';
comment on table public.site_metrics is 'Public aggregate evidence with no visitor or feedback details.';
